// Generated by "go_enum -types=ExternalLanguages -output=external_languages.gen.go -input=external_languages.go"; DO NOT EDIT.
// https://github.com/iDevelopThings/go-enum
package main

import (
	. "github.com/iDevelopThings/go-enum/enum"
)

/**
 * START OF ExternalLanguage
 */

type ExternalLanguage struct {
	Enum[string]
}

func (e ExternalLanguage) GetAll() ExternalLanguagesContainer {
	return ExternalLanguages
}

type ExternalLanguagesContainer struct {
	EnumContainer[ExternalLanguage, string]

	// PHP bindings
	PHP ExternalLanguage
	// JS bindings
	JS ExternalLanguage
}

var externalLanguagesContainerMap = map[string]ExternalLanguage{
	"PHP": ExternalLanguage{
		Enum: Enum[string]{
			Name:        "PHP",
			Value:       "PHP",
			Description: "PHP bindings",
		},
	},
	"JS": ExternalLanguage{
		Enum: Enum[string]{
			Name:        "JS",
			Value:       "JS",
			Description: "JS bindings",
		},
	},
}

var ExternalLanguages = ExternalLanguagesContainer{
	EnumContainer: *NewEnumContainer[ExternalLanguage, string](
		externalLanguagesContainerMap, compareExternalLanguages,
	),
	PHP: externalLanguagesContainerMap["PHP"],
	JS:  externalLanguagesContainerMap["JS"],
}
